### ISSUE TITLE
Keeps crashing and i cant understand the reason

### ISSUE THREAD

**Issue by MirayXS** [MrDarkShadoow/Discord-Spotify-Rpc#5]
hi, whenever i tried it would crash everytime.
I tried many times it didn't work.
Can you please try to run it?

**Comment by MrDarkShadoow** [comment]
> hi, whenever i tried it would crash everytime. I tried many times it didn't work. Can you please try to run it?

![image](https://user-images.githubusercontent.com/98183554/168641012-46fd7a04-fc95-48ae-b683-a7db6666bd49.png)

if you need help contact me on discord
